apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nycjoker-poi-backend-app-dev
  annotations:
    argocd/app-name: nycjoker-poi-backend-app-dev
    backstage.io/kubernetes-id: nycjoker-poi-backend-app
    backstage.io/kubernetes-namespace: nycjoker
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rosa916-rvhvd/nycjoker-backend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - java
    - quarkus
    - maven
    - workshop
  links:
    - url: https://console-openshift-console.apps.rosa916.9nln.p1.openshiftapps.com/dev-pipelines/ns/nycjoker/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.rosa916.9nln.p1.openshiftapps.com/k8s/ns/nycjoker/deployments/nycjoker-poi-backend-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.rosa916.9nln.p1.openshiftapps.com/#https://github.com/rosa916-rvhvd/nycjoker-backend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/nycjoker"
  system: workshop-system-nycjoker
  providesApis:
    - backend-api-nycjoker
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-nycjoker
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/nycjoker"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: backend-api-nycjoker
  description: API surface used by workshop attendees to initialize and load parks data
  links:
    - url: http://nycjoker-poi-backend-app-nycjoker.apps.rosa916.9nln.p1.openshiftapps.com/q/swagger-ui
      title: Swagger UI
      icon: web
    - url: https://github.com/rosa916-rvhvd/nycjoker-backend/tree/main/src/main/resources/META-INF/openapi.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: production
  owner: "user:default/nycjoker"
  system: workshop-system-nycjoker
  definition:
    $text: https://github.com/rosa916-rvhvd/nycjoker-backend/tree/main/src/main/resources/META-INF/openapi.yaml
